build: off

# Specify which branches/tags that we do not want to be built: r5.0.0-M5
branches:
  except:
    - /^r\d.*$/

install:
# JDK installation via: https://chocolatey.org/packages/jdk11
  - cinst jdk11 -params 'installdir=C:\\jdk11'
  - SET JAVA_HOME="C:\jdk11"
# Or use pre-installed JDK
#  - SET JAVA_HOME="C:\Program Files\Java\jdk10"
  - SET PATH=%JAVA_HOME%\bin;%PATH%

test_script:
  - gradlew --version
  - gradlew --scan --stacktrace build publishToMavenLocal
  - gradlew --scan --stacktrace -Dplatform.tooling.support.tests.enabled=true build
